#######################################################################################################################
# Logging
#######################################################################################################################
logging:
  file: launchpad-api.log

#######################################################################################################################
# Spring Configuration
#######################################################################################################################
spring:

  application:
    name: Launchpad API

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/launchpad?useSSL=false&autoReconnect=true
    username: launchpad
    password: launchpad
    driver-class-name: com.mysql.jdbc.Driver
    #initialSize: 10
    #maxActive: 50
    #maxIdle: 30
    #maxWait: 100000
    #removeAbandoned: true
    #removeAbandonedTimeout: 60
    #logAbandoned: true
    #validationQuery: SELECT 1
    #testOnBorrow: true
    #testWhileIdle: true
    #testOnReturn: true
    #minEvictableIdleTimeMillis: 30000
    #timeBetweenEvictionRunsMillis: 30000

#######################################################################################################################
# Spring Boot Web / Embedded Tomcat
#######################################################################################################################
server:
  port: 8080
  contextPath: /api

#######################################################################################################################
# Spring Security
#######################################################################################################################
security:
  oauth2:
    resource:
      id: launchpad
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4REj5EYufU5OUnv9nij+
          j9irwALL3BwX9XxB7oDx3uj93P5h8rzTTdG/suaG3aBqRr5rqXpmTgwG1nf6FBfR
          8kiPp9R196cAT9g4OInsdNbux7oy5akUVsRo9pagEL0JB7eGbASi0z5A38QkpbjB
          MhIN0W9zwghsGNbf7N6wTVQN1NFHDW9zMdWUS9VBPeEGUZAMkKElGltHVhCdJGBf
          OdriLIO2KdimjO5q9Q9+qG2B96DFGNYvmuDlDLM11Q2fsre305CV1HN0vQulLhlr
          MJo9QdZt1g2d1VN5uIKid5dxWTAuUvJhgla6yCaTfYeV1OGq5C3DFV7tKDGNAIXL
          TQIDAQAB
          -----END PUBLIC KEY-----

  # FOR PRODUCTION: The following MUST be overridden to ensure secrecy of the passwords for the keystore and private
  # See where you can override at https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
  jwt:
    key-store-filename: jwt.jks
    key-store-password: changeme
    private-key-name: jwt
    private-key-password: changeme
