#######################################################################################################################
# Application
#######################################################################################################################
app:
  name: Voyage
  contact-support:
    email: support@LighthouseSoftware.com
    phone: 651-888-6021
    website: http://LighthouseSoftware.com/support
  default-country: US

#######################################################################################################################
# Logging
#######################################################################################################################
logging:
  file: voyage-api.log

#######################################################################################################################
# Liquibase Database Migration
#######################################################################################################################
liquibase.contexts: '!test'

#######################################################################################################################
# Spring Configuration
#######################################################################################################################
spring:

  application:
    name: Voyage API

  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.mail.MailSenderAutoConfiguration

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/voyage?useSSL=false&autoReconnect=true
    username: voyage
    password: voyage
    driver-class-name: com.mysql.jdbc.Driver
    #initialSize: 10
    #maxActive: 50
    #maxIdle: 30
    #maxWait: 100000
    #removeAbandoned: true
    #removeAbandonedTimeout: 60
    #logAbandoned: true
    #validationQuery: SELECT 1
    #testOnBorrow: true
    #testWhileIdle: true
    #testOnReturn: true
    #minEvictableIdleTimeMillis: 30000
    #timeBetweenEvictionRunsMillis: 30000

  mail:
      host: localhost
      port: 3025
      overrideAddress: testmsg@LighthouseSoftware.com

  freemarker:
    template-loader-path: classpath:/email/
    charset: UTF-8
    suffix: .ftl

#######################################################################################################################
# Spring Boot Web / Embedded Tomcat
#######################################################################################################################
server:
  port: 8080
  contextPath: /

#######################################################################################################################
# Security
#######################################################################################################################
security:

  ignored: /resources/**, /webjars/**, /docs, /docs/**
  permitAll: /login, /api/status, /api/**/account

  # FOR PRODUCTION: The following MUST be overridden to ensure secrecy of the passwords for the keystore and private
  # See where you can override at https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
  key-store:
    filename: keystore.jks
    password: changeme

  crypto:
    private-key-name: asymmetric
    private-key-password: changeme

  # FOR PRODUCTION: The following MUST be overridden to ensure secrecy of the passwords for the keystore and private
  # See where you can override at https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
  jwt:
    private-key-name: jwt
    private-key-password: changeme

  # FOR PRODUCTION: The following MUST be overridden to ensure secrecy of the passwords for the keystore and private
  # See where you can override at https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
  oauth2:
    resource:
      id: voyage
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyfgFBATB9oJjCUOVtwsr
          s8H6b8jiwl1gAuOVEHCgQbxuZPJ+YvcJad2xsEQLKbZBatbWF8gQIE0YNPW27niN
          CrH9QKYyFih5Ko2B8M5xbDr1L/AiQUsVwiqBmyj0krswacF9zRHwKHurFoxihhP0
          L6/NYrny8f5No8DNCC/abDYGFksqCE6gzLVB8moFGGcOk71l4CHJmlVrGS/Ec5Jj
          ktQuBza5RwiSb62PYiHGy5mLl8owdH0m0PCaXZBO2QzPbecFp2+W/5aXfIRchcjH
          Itcr8HKAqDO13XDo+xtqtVkFEn6hXXj5YESMkwukbWopDWOpfcGoQZStMhAEN7Xt
          zQIDAQAB
          -----END PUBLIC KEY-----

  user-verification:
    exclude-resources: /oauth/**, /resources/**, /webjars/**, /docs/**, /login, /api/**/verify, /api/**/verify/send, /WEB-INF/jsp/**.jsp, /api/**/account
    verify-code-expire-minutes: 30

  cors:
    access-control-allow-headers: Accept, Authorization, Content-Type, Cookie, Origin, User-Agent

#######################################################################################################################
# AWS Configuration to send Emails and SMS
#######################################################################################################################
cloud:
  aws:
    enabled: false
    stack:
      auto: false
    credentials:
      accessKey: ENTER YOUR CODE
      secretKey: ENTER YOUR CODE
    region:
      auto: true
      static: us-east-1